### ISSUE TITLE
Problem executing validation step in setup

### ISSUE THREAD

**Issue by d4vsanchez** [kentcdodds/react-suspense#56]
Hi! I've been trying to execute `npm run setup --silent` in order to configure the project but I'm getting the following error in the Project Validation step:

```
Oops! Something went wrong! :(

ESLint: 7.20.0

Error: Failed to load plugin 'import' declared in 'package.json » eslint-config-react-app': Cannot find module '/Users/__user__/epic-react/react-suspense/node_modules/eslint-plugin-import/node_modules/doctrine/lib/doctrine.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/__user__/epic-react/react-suspense/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/__user__/epic-react/react-suspense/node_modules/eslint-plugin-import/lib/ExportMap.js:645:130)
    at Module._compile (/Users/__user__/epic-react/react-suspense/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

I'm not sure how to fix this or if there's a workaround, but I'd really appreciate any help.

This is the information about my NodeJS installation:
- Node: **v14.16.0**
- NPM: **7.6.0**

**Comment by kentcdodds** [comment]
Hi @d4vsanchez, I just tried and everything works fine with npm v6. Could you try with npm v6?

**Comment by kentcdodds** [comment]
Interestingly, I tried with npm v7.6.1 and it worked fine as well... I'm not sure what the issue could be in this case. Sorry 😬

**Comment by kentcdodds** [comment]
I just made an update to the setup script that *might* help: https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733/revisions#diff-a38349e26cd88bc390da3dd2ce99890c25f651f5af8edd9e95a77577032ce9c1

Go ahead and start over from scratch (delete the repo locally) and let me know how it works for you:

```
git clone https://github.com/kentcdodds/react-suspense.git
cd react-suspense
node setup
```

Thanks!

**Comment by d4vsanchez** [comment]
Everything is perfect now. I really appreciate your help! Now I can start looking at that module!
